# Config file for automatic testing at travis-ci.org

sudo: false
language: python

python:
    - '3.6'

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - pip install tox-travis

script: tox

cache: pip
